# Generated by Django 4.0.5 on 2022-07-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tom', models.CharField(max_length=255)),
                ('vetor', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
